export enum GameType {
  counter = 'counter',
  answer = 'answer',
  tiltProgressBar = 'tiltProgressBar',
  timeDependent = 'timeDependent',
  gyroColor = 'gyroColor',
  paintProgressBar = 'paintProgressBar',
  locationDependent = 'locationDependent',
  clicker = 'clicker',
  secretMenuItem = 'secretMenuItem',
  dragProgressBar = 'dragProgressBar',
  dragPlusButton = 'dragPlusButton',
  typeStidi = 'typeStidi',
  spinProgressBar = 'spinProgressBar',
  hacker = 'hacker',
}
